
function importAll(r) {
    let stored = {};
    r.keys().map((item) => { stored[item.replace('./', '')] = r(item); });
    return stored;
}

const Avatarz = importAll(require.context('../Images/artists_icons', true, /\.(png|jpe?g|svg)$/));
const Imagingz = importAll(require.context('../Music files', true, /\.(png|jpe?g|svg)$/))


const Anne_marie = Avatarz['Anne-Marie.jpg'].default
const Marshmello = Avatarz['Marshmellow.jpg'].default
const Taylor = Avatarz['Taylor Swift.jpg'].default
const Charlie = Avatarz['Charlie Puth.jpg'].default
const Ed = Avatarz['Ed-Sheeran.jpg'].default
const Billie = Avatarz['Billie-Ellish.jpg'].default
const Shawn = Avatarz['Shawn-Mendes.jpg'].default
const Justin = Avatarz['Justin Bieber.jpg'].default


 export const Music = [
    {
        id:1,
        name:'Anyone',
        Artist:'Justin Bieber',
        Artist_image:Justin,
        Preview:Imagingz['Justin Bieber/thumbnail/Anyone.jpg'],
        Views:'5261522',
        Likes:'251409',
        duration:'3:15',
    },
    {
        id:2,
        name:'At Least For Now',
        Artist:'Justin Bieber',
        Artist_image:Justin,
        Preview:Imagingz['Justin Bieber/thumbnail/At Least For Now.jpg'],
        Views:'2918536',
        Likes:'84066',
        duration:'2:30',
    },
    {
        id:3,
        name:'Available',
        Artist:'Justin Bieber',
        Artist_image:Justin,
        Preview:Imagingz['Justin Bieber/thumbnail/Available.jpg'],
        Views:'5653556',
        Likes:'92393',
        duration:'3:15',
    },
    {
        id:4,
        name:'Changes',
        Artist:'Justin Bieber',
        Artist_image:Justin,
        Preview:Imagingz['Justin Bieber/thumbnail/Changes.jpg'],
        Views:'9034036',
        Likes:'309083',
        duration:'2:16',
    },
    {
        id:5,
        name:'Hold On',
        Artist:'Justin Bieber',
        Artist_image:Justin,
        Preview:Imagingz['Justin Bieber/thumbnail/Hold On.jpg'],
        Views:'34559916',
        Likes:'1464780',
        duration:'3:31',
    },
    {
        id:6,
        name:'Holy',
        Artist:'Justin Bieber',
        Artist_image:Justin,
        Preview:Imagingz['Justin Bieber/thumbnail/Holy.jpg'],
        Views:'139880158',
        Likes:'3566326',
        duration:'3:33',
    },
    {
        id:7,
        name:'Lifetime',
        Artist:'Justin Bieber',
        Artist_image:Justin,
        Preview:Imagingz['Justin Bieber/thumbnail/Lifetime.jpg'],
        Views:'1182833',
        Likes:'71849',
        duration:'3:25',
    },
    {
        id:8,
        name:'Off my Face',
        Artist:'Justin Bieber',
        Artist_image:Justin,
        Preview:Imagingz['Justin Bieber/thumbnail/Off my face.jpg'],
        Views:'3046351',
        Likes:'120652',
        duration:'3:17',
    },
    {
        id:9,
        name:'Peaches',
        Artist:'Justin Bieber',
        Artist_image:Justin,
        Preview:Imagingz['Justin Bieber/thumbnail/Peaches.jpg'],
        Views:'73524398',
        Likes:'2353767',
        duration:'3:18',
    },
    {
        id:10,
        name:'Unstable',
        Artist:'Justin Bieber',
        Artist_image:Justin,
        Preview:Imagingz['Justin Bieber/thumbnail/Unstable.jpg'],
        Views:'3962486',
        Likes:'160984',
        duration:'3:19',
    },
    {
        id:11,
        name:'Attention',
        Artist:'Charlie Puth',
        Artist_image:Charlie,
        Preview:Imagingz['Carlie Puth/Thumbnails/Attention.jpg'],
        Views:'1233523464',
        Likes:'8501302',
        duration:'3:52',
    },
    {
        id:12,
        name:'Empty Cups',
        Artist:'Charlie Puth',
        Artist_image:Charlie,
        Preview:Imagingz['Carlie Puth/Thumbnails/Empty cups.jpg'],
        Views:'6866224',
        Likes:'65831',
        duration:'2:52',
    },
    {
        id:13,
        name:'How Long',
        Artist:'Charlie Puth',
        Artist_image:Charlie,
        Preview:Imagingz['Carlie Puth/Thumbnails/How Long.jpg'],
        Views:'609424130',
        Likes:'7984464',
        duration:'3:31',
    },
    {
        id:14,
        name:'I Won\'t Tell A Soul',
        Artist:'Charlie Puth',
        Artist_image:Charlie,
        Preview:Imagingz['Carlie Puth/Thumbnails/I Wont Tell A Soul.jpg'],
        Views:'1213684',
        Likes:'20784',
        duration:'3:14',
    },
    {
        id:15,
        name:'LA Girls',
        Artist:'Charlie Puth',
        Artist_image:Charlie,
        Preview:Imagingz['Carlie Puth/Thumbnails/La Girl.jpg'],
        Views:'15561177',
        Likes:'146818',
        duration:'3:17',
    },
    {
        id:16,
        name:'Patient',
        Artist:'Charlie Puth',
        Artist_image:Charlie,
        Preview:Imagingz['Carlie Puth/Thumbnails/Patient.jpg'],
        Views:'21754618',
        Likes:'146439',
        duration:'3:11',
    },
    {
        id:17,
        name:'Slow It Down',
        Artist:'Charlie Puth',
        Artist_image:Charlie,
        Preview:Imagingz['Carlie Puth/Thumbnails/Slow It Down.jpg'],
        Views:'5750122',
        Likes:'65110',
        duration:'3:11',
    },
    {
        id:18,
        name:'Some Type of Love',
        Artist:'Charlie Puth',
        Artist_image:Charlie,
        Preview:Imagingz['Carlie Puth/Thumbnails/Some Types of Love.jpg'],
        Views:'20850963',
        Likes:'131574',
        duration:'3:06',
    },
    {
        id:19,
        name:'Suffer',
        Artist:'Charlie Puth',
        Artist_image:Charlie,
        Preview:Imagingz['Carlie Puth/Thumbnails/Suffer.jpg'],
        Views:'20246248',
        Likes:'161052',
        duration:'3:37',
    },
    {
        id:20,
        name:'The Way I Am',
        Artist:'Charlie Puth',
        Artist_image:Charlie,
        Preview:Imagingz['Carlie Puth/Thumbnails/The way I am.jpg'],
        Views:'56051956',
        Likes:'893745',
        duration:'3:06',
    },
    {
        id:21,
        name:'2002',
        Artist:'Anne Marie',
        Artist_image:Anne_marie,
        Preview:Imagingz['Anne Marie/Thumbnails/2002.jpg'],
        Views:'522194599',
        Likes:'3719834',
        duration:'3:13',
    },
    {
        id:22,
        name:'Cry',
        Artist:'Anne Marie',
        Artist_image:Anne_marie,
        Preview:Imagingz['Anne Marie/Thumbnails/Cry.jpg'],
        Views:'2809086',
        Likes:'3711',
        duration:'3:37',
    },
    {
        id:23,
        name:'Heavy',
        Artist:'Anne Marie',
        Artist_image:Anne_marie,
        Preview:Imagingz['Anne Marie/Thumbnails/Heavy.jpg'],
        Views:'16144941',
        Likes:'181360',
        duration:'3:02',
    },
    {
        id:24,
        name:'Then',
        Artist:'Anne Marie',
        Artist_image:Anne_marie,
        Preview:Imagingz['Anne Marie/Thumbnails/Then.jpg'],
        Views:'9485738',
        Likes:'86996',
        duration:'3:35',
    },
    {
        id:25,
        name:'To Be Young',
        Artist:'Anne Marie',
        Artist_image:Anne_marie,
        Preview:Imagingz['Anne Marie/Thumbnails/To Be Young.jpg'],
        Views:'15091355',
        Likes:'464969',
        duration:'3:36',
    },
    {
        id:26,
        name:'Trigger',
        Artist:'Anne Marie',
        Artist_image:Anne_marie,
        Preview:Imagingz['Anne Marie/Thumbnails/Trigger.jpg'],
        Views:'379819',
        Likes:'5883',
        duration:'3:14',
    },
    {
        id:27,
        name:'Don\'t Play',
        Artist:'Anne Marie',
        Artist_image:Anne_marie,
        Preview:Imagingz['Anne Marie/Thumbnails/Don\'t play.jpg'],
        Views:'20864266',
        Likes:'789961',
        duration:'3:18',
    },
    
    {
        id:28,
        name:'Beautiful People',
        Artist:'Ed Sheeran',
        Artist_image:Ed,
        Preview:Imagingz['Ed Sheeran/Thumbnail/Beautiful People.jpg'],
        Views:'291014260',
        Likes:'2462216',
        duration:'3:19',
    },
    {
        id:29,
        name:'Dive',
        Artist:'Ed Sheeran',
        Artist_image:Ed,
        Preview:Imagingz['Ed Sheeran/Thumbnail/Dive.jpg'],
        Views:'451529720',
        Likes:'2619081',
        duration:'3:58',
    },
    {
        id:30,
        name:'Eraser',
        Artist:'Ed Sheeran',
        Artist_image:Ed,
        Preview:Imagingz['Ed Sheeran/Thumbnail/Eraser.jpg'],
        Views:'58751989',
        Likes:'361230',
        duration:'3:47',
    },
    {
        id:31,
        name:'Galway Girl',
        Artist:'Ed Sheeran',
        Artist_image:Ed,
        Preview:Imagingz['Ed Sheeran/Thumbnail/Galway Girl.jpg'],
        Views:'512871544',
        Likes:'3479665',
        duration:'2:53',
    },
    {
        id:32,
        name:'Happier',
        Artist:'Ed Sheeran',
        Artist_image:Ed,
        Preview:Imagingz['Ed Sheeran/Thumbnail/Happier.jpg'],
        Views:'354855469',
        Likes:'4648890',
        duration:'3:28',
    },
    {
        id:33,
        name:'I Don\'t Care',
        Artist:'Ed Sheeran',
        Artist_image:Ed,
        Preview:Imagingz['Ed Sheeran/Thumbnail/I Don\'t Care.jpg'],
        Views:'458560797',
        Likes:'5662584',
        duration:'3:37',
    },
    {
        id:34,
        name:'Nancy Mulligan',
        Artist:'Ed Sheeran',
        Artist_image:Ed,
        Preview:Imagingz['Ed Sheeran/Thumbnail/Nancy Mulligan.jpg'],
        Views:'100868430',
        Likes:'494831',
        duration:'3:00',
    },
    {
        id:35,
        name:'New Man',
        Artist:'Ed Sheeran',
        Artist_image:Ed,
        Preview:Imagingz['Ed Sheeran/Thumbnail/New Man.jpg'],
        Views:'64401047',
        Likes:'307036',
        duration:'3:10',
    },
    {
        id:36,
        name:'Put It All On',
        Artist:'Ed Sheeran',
        Artist_image:Ed,
        Preview:Imagingz['Ed Sheeran/Thumbnail/Put It All on.jpg'],
        Views:'51074018',
        Likes:'791144',
        duration:'3:18',
    },
    {
        id:37,
        name:'Shape of You',
        Artist:'Ed Sheeran',
        Artist_image:Ed,
        Preview:Imagingz['Ed Sheeran/Thumbnail/Shape of you.jpg'],
        Views:'5254555704',
        Likes:'26380232',
        duration:'4:24',
    },
    {
        id:38,
        name:'Bad Guy',
        Artist:'Billie Eilish',
        Artist_image:Billie,
        Preview:Imagingz['Billie Eilish/Thumbnails/Bad Guy.jpg'],
        Views:'1078882425',
        Likes:'16032285',
        duration:'3:25',
    },
    {
        id:39,
        name:'Buy a Friend',
        Artist:'Billie Eilish',
        Artist_image:Billie,
        Preview:Imagingz['Billie Eilish/Thumbnails/Bury a Friend.jpg'],
        Views:'403264892',
        Likes:'7507904',
        duration:'3:32',
    },
    {
        id:40,
        name:'COPYCAT',
        Artist:'Billie Eilish',
        Artist_image:Billie,
        Preview:Imagingz['Billie Eilish/Thumbnails/COPYCAT.jpg'],
        Views:'135449398',
        Likes:'1945215',
        duration:'3:19',
    },
    {
        id:41,
        name:'Hostage',
        Artist:'Billie Eilish',
        Artist_image:Billie,
        Preview:Imagingz['Billie Eilish/Thumbnails/Hostage.jpg'],
        Views:'113853952',
        Likes:'2005851',
        duration:'3:54',
    },
    {
        id:42,
        name:'Idontwannabeyou   anymore',
        Artist:'Billie Eilish',
        Artist_image:Billie,
        Preview:Imagingz['Billie Eilish/Thumbnails/Idontwannabeyouanymore.jpg'],
        Views:'259971195',
        Likes:'3402475',
        duration:'3:25',
    },
    {
        id:43,
        name:'I love you',
        Artist:'Billie Eilish',
        Artist_image:Billie,
        Preview:Imagingz['Billie Eilish/Thumbnails/I Love You.jpg'],
        Views:'34706315',
        Likes:'816780',
        duration:'4:59',
    },
    {
        id:44,
        name:'Lovely',
        Artist:'Billie Eilish',
        Artist_image:Billie,
        Preview:Imagingz['Billie Eilish/Thumbnails/Lovely.jpg'],
        Views:'1143138518',
        Likes:'16684893',
        duration:'3:20',
    },
    {
        id:45,
        name:'No Time To Die',
        Artist:'Billie Eilish',
        Artist_image:Billie,
        Preview:Imagingz['Billie Eilish/Thumbnails/No Time To Die.jpg'],
        Views:'99022250',
        Likes:'2265901',
        duration:'4:03',
    },
    {
        id:46,
        name:'Therefore I Am',
        Artist:'Billie Eilish',
        Artist_image:Billie,
        Preview:Imagingz['Billie Eilish/Thumbnails/Therefore I Am.jpg'],
        Views:'148805625',
        Likes:'6079239',
        duration:'4:59',
    },
    {
        id:47,
        name:'you should see me in a crown',
        Artist:'Billie Eilish',
        Artist_image:Billie,
        Preview:Imagingz['Billie Eilish/Thumbnails/you should see me in a crown.jpg'],
        Views:'87249293',
        Likes:'2475750',
        duration:'3:12',
    },
    {
        id:48,
        name:'Blank Space',
        Artist:'Taylor Swift',
        Artist_image:Taylor,
        Preview:Imagingz['Taylor Swift/Thumbnails/Blank Space.jpg'],
        Views:'2750413275',
        Likes:'11454927',
        duration:'4:33',
    },
    {
        id:49,
        name:'Chanpagne problems',
        Artist:'Taylor Swift',
        Artist_image:Taylor,
        Preview:Imagingz['Taylor Swift/Thumbnails/Chanpagne problems.jpg'],
        Views:'14275314',
        Likes:'320949',
        duration:'4:07',
    },
    {
        id:50,
        name:'no body, no crime',
        Artist:'Taylor Swift',
        Artist_image:Taylor,
        Preview:Imagingz['Taylor Swift/Thumbnails/no body, no crime.jpg'],
        Views:'10672125',
        Likes:'272838',
        duration:'3:37',
    },
    {
        id:51,
        name:'The last great American dynasty',
        Artist:'Taylor Swift',
        Artist_image:Taylor,
        Preview:Imagingz['Taylor Swift/Thumbnails/The last great American dynasty.jpg'],
        Views:'14146516',
        Likes:'260438',
        duration:'3:51',
    },
    {
        id:52,
        name:'The Man',
        Artist:'Taylor Swift',
        Artist_image:Taylor,
        Preview:Imagingz['Taylor Swift/Thumbnails/The Man.jpg'],
        Views:'54031000',
        Likes:'1544514',
        duration:'4:14',
    },
    {
        id:53,
        name:'Willow',
        Artist:'Taylor Swift',
        Artist_image:Taylor,
        Preview:Imagingz['Taylor Swift/Thumbnails/Willow.jpg'],
        Views:'69327079',
        Likes:'1699053',
        duration:'4:12',
    },
    {
        id:54,
        name:'You Belong With Me',
        Artist:'Taylor Swift',
        Artist_image:Taylor,
        Preview:Imagingz['Taylor Swift/Thumbnails/You Belong With Me.jpg'],
        Views:'1177424158',
        Likes:'6910441',
        duration:'3:49',
    },
    {
        id:55,
        name:'You Need To Calm Down',
        Artist:'Taylor Swift',
        Artist_image:Taylor,
        Preview:Imagingz['Taylor Swift/Thumbnails/You Need To Calm Down.jpg'],
        Views:'243440872',
        Likes:'3980723',
        duration:'3:29',
    },
    {
        id:56,
        name:'Imagination',
        Artist:'Shawn Mendes',
        Artist_image:Shawn,
        Preview:Imagingz['Shawn Mendes/Thumbnail/Imagination.jpg'],
        Views:'33123801',
        Likes:'143364',
        duration:'3:38',
    },
    {
        id:57,
        name:'AfterState',
        Artist:'Shawn Mendes',
        Artist_image:Shawn,
        Preview:Imagingz['Shawn Mendes/Thumbnail/AfterState.jpg'],
        Views:'76519617',
        Likes:'824918',
        duration:'3:09',
    },
    {
        id:58,
        name:'Air',
        Artist:'Shawn Mendes',
        Artist_image:Shawn,
        Preview:Imagingz['Shawn Mendes/Thumbnail/Air.jpg'],
        Views:'131078164',
        Likes:'141885',
        duration:'3:15',
    },
    {
        id:59,
        name:'A Little Too Much',
        Artist:'Shawn Mendes',
        Artist_image:Shawn,
        Preview:Imagingz['Shawn Mendes/Thumbnail/A Little Too Much.jpg'],
        Views:'16076446',
        Likes:'241452',
        duration:'3:06',
    },
    {
        id:60,
        name:'Crazy',
        Artist:'Shawn Mendes',
        Artist_image:Shawn,
        Preview:Imagingz['Shawn Mendes/Thumbnail/Crazy.jpg'],
        Views:'13914755',
        Likes:'107973',
        duration:'3:11',
    },
    {
        id:61,
        name:'I Don\'t Even Know Your Name',
        Artist:'Shawn Mendes',
        Artist_image:Shawn,
        Preview:Imagingz['Shawn Mendes/Thumbnail/I Don\'t Even Know Your Name.jpg'],
        Views:'19510471',
        Likes:'135837',
        duration:'3:00',
    },
    {
        id:62,
        name:'Never Be Alone',
        Artist:'Shawn Mendes',
        Artist_image:Shawn,
        Preview:Imagingz['Shawn Mendes/Thumbnail/Never Be Alone.jpg'],
        Views:'4875652',
        Likes:'90532',
        duration:'3:35',
    },
    {
        id:63,
        name:'Stings',
        Artist:'Shawn Mendes',
        Artist_image:Shawn,
        Preview:Imagingz['Shawn Mendes/Thumbnail/Strings.jpg'],
        Views:'11938777',
        Likes:'118565',
        duration:'3:12',
    },
    {
        id:64,
        name:'Wonder',
        Artist:'Shawn Mendes',
        Artist_image:Shawn,
        Preview:Imagingz['Shawn Mendes/Thumbnail/Wonder.jpg'],
        Views:'79487004',
        Likes:'2262389',
        duration:'3:14',
    },
    {
        id:65,
        name:'Youth',
        Artist:'Shawn Mendes',
        Artist_image:Shawn,
        Preview:Imagingz['Shawn Mendes/Thumbnail/Youth.jpg'],
        Views:'76449352',
        Likes:'1264600',
        duration:'3:23',
    },
    {
        id:66,
        name:'Alone',
        Artist:'Marshmello',
        Artist_image:Marshmello,
        Preview:Imagingz['Marshmellow/Thumbnails/Alone.jpg'],
        Views:'2016096633',
        Likes:'20073136',
        duration:'3:19',
    },
    {
        id:67,
        name:'FRIENDS',
        Artist:'Marshmello',
        Artist_image:Marshmello,
        Preview:Imagingz['Marshmellow/Thumbnails/FRIENDS.jpg'],
        Views:'849181373',
        Likes:'10032566',
        duration:'3:51',
    },
    {
        id:68,
        name:'Moving On',
        Artist:'Marshmello',
        Artist_image:Marshmello,
        Preview:Imagingz['Marshmellow/Thumbnails/Moving On.jpg'],
        Views:'264270302',
        Likes:'2440444',
        duration:'2:59',
    },
    {
        id:69,
        name:'Summer',
        Artist:'Marshmello',
        Artist_image:Marshmello,
        Preview:Imagingz['Marshmellow/Thumbnails/Summer.jpg'],
        Views:'370620879',
        Likes:'3400044',
        duration:'2:50',
    },
    {
        id:70,
        name:'Blocks',
        Artist:'Marshmello',
        Artist_image:Marshmello,
        Preview:Imagingz['Marshmellow/Thumbnails/Blocks.jpg'],
        Views:'163848830',
        Likes:'1936950',
        duration:'3:26',
    },
    {
        id:71,
        name:'Power',
        Artist:'Marshmello',
        Artist_image:Marshmello,
        Preview:Imagingz['Marshmellow/Thumbnails/Power.jpg'],
        Views:'43991949',
        Likes:'662325',
        duration:'2:52',
    },
    {
        id:72,
        name:'Imagine',
        Artist:'Marshmello',
        Artist_image:Marshmello,
        Preview:Imagingz['Marshmellow/Thumbnails/Imagine.jpg'],
        Views:'23215442',
        Likes:'465824',
        duration:'2:55',
    },
    {
        id:73,
        name:'Paralyzed',
        Artist:'Marshmello',
        Artist_image:Marshmello,
        Preview:Imagingz['Marshmellow/Thumbnails/Paralyzed.jpg'],
        Views:'34818488',
        Likes:'820008',
        duration:'3:09',
    },
    {
        id:74,
        name:'Tell Me',
        Artist:'Marshmello',
        Artist_image:Marshmello,
        Preview:Imagingz['Marshmellow/Thumbnails/Tell me.jpg'],
        Views:'55613596',
        Likes:'835123',
        duration:'2:39',
    },
    {
        id:75,
        name:'Find Me',
        Artist:'Marshmello',
        Artist_image:Marshmello,
        Preview:Imagingz['Marshmellow/Thumbnails/Find me.jpg'],
        Views:'116586975',
        Likes:'1494458',
        duration:'3:07',
    },
    {
        id:76,
        name:'Together',
        Artist:'Marshmello',
        Artist_image:Marshmello,
        Preview:Imagingz['Marshmellow/Thumbnails/Together.jpg'],
        Views:'290224222',
        Likes:'3090106',
        duration:'3:48',
    },
    {
        id:77,
        name:'Talk it Back',
        Artist:'Marshmello',
        Artist_image:Marshmello,
        Preview:Imagingz['Marshmellow/Thumbnails/Talk it back.jpg'],
        Views:'138081543',
        Likes:'1460013',
        duration:'3:14',
    },

]